config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'
  get 'doctors/home'
  get 'doctors/new', to: 'doctors#new'
  get 'doctors/create'
  get 'doctors/login', to: 'doctors#login'
  get '/patients' => 'patients#index'
  get 'patients/home'
  get 'patients/new', to: 'patients#new'
  get 'patients/create'
  get 'patients/login', to: 'patients#login'
  post '/login', to: 'sessions#create'
  get 'sessions/welcome'
  get 'appointments/new'
  get 'prescriptions/new'
  post '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :appointments
  resources :drugs
  resources :prescriptions
  resources :licenses
  resources :patients, only: [:new, :create, :show, :home]
  resources :doctors
  
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'

  # get ‘patients/signup’ => ‘patients#new’
  # post ‘/patients’ => ‘patients#create’

  # get ‘doctors/signup’ => ‘doctors#new’
  # post ‘/doctors’ => ‘doctors#create’

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
  

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :patient
    belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_secure_password

    belongs_to :license

    has_many :prescriptions
    has_many :drugs, through: :prescriptions

    has_many :appointments
    has_many :patients, through: :appointments

    validates :license_id, uniqueness: true
end

app/models/drug.rb
class Drug < ApplicationRecord
    has_many :prescriptions
    has_many :doctors, through: :prescriptions
    has_many :patients, through: :prescriptions
end

app/models/license.rb
class License < ApplicationRecord
    # belongs_to :doctor

    # def validate(record)
    #     if record != License.all.find_by(number:)
    #         record.errors[:base] << "This is not a valid doctor license!"
    #     end
    # end
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_secure_password

    has_many :appointments
    has_many :doctors, through: :appointments

    has_many :prescriptions
    has_many :drugs, through: :prescriptions

    validates :name, :email, :password, presence: true
    validates :email, uniqueness: true
end

app/models/prescription.rb
class Prescription < ApplicationRecord
    belongs_to :doctor
    belongs_to :patient
    belongs_to :drug
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?

    def current_user
        if session[:patient_id]
            @patient = Patient.find(session[:patient_id])
        elsif session[:doctor_id]
            @doctor = Doctor.find(session[:doctor_id])
        end
    end

    def logged_in?
        !!current_user 
    end

    def authorized
        redirect_to '/welcome' unless logged_in?
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    before_action :get_patient, only: [:create, :new]

    def new
        @doctors = Doctor.all
        @appointment = Appointment.new
    end

    def create
        @appointment = Appointment.new(appointment_params)
        @appointment.patient = @patient
        @appointment.save
    end

    def destroy
        @appointment = Appointment.where(id: params[:id]).first
        @appointment.destroy
    end

    private

    def get_patient
        @patient = Patient.find(session[:patient_id])
    end

    def appointment_params
        params.require(:appointment).permit(:appointment_time, :doctor_id, :patient_id)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :home, :login]

  def home
  end

  def new
    @doctor = Doctor.new
  end

  def show
    @patients = Patient.all
    @doctor = Doctor.find(params[:id])
  end

  def login
  end

  def create
    @doctor = Doctor.new(doctor_params)
    license = License.find_by(number: params[:doctor][:license_id].to_i)
    @doctor.license_id = license.id
    if @doctor.valid?
      @doctor.save
      session[:doctor_id] = @doctor.id
      redirect_to doctors_login_path
    else
      redirect_to new_doctor_path
    end
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name, :email, :password)
  end
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController

    def new
        @drug = Drug.new
    end

    def create
        @drug.save
    end

    def destroy
        @drug = Drug.where(id: params[:id]).first
        @drug.destroy
    end

    private

    def drug_params
        params.require(:drug).permit(:name)
    end
end

app/controllers/licenses_controller.rb
class LicensesController < ApplicationController

    def new
        @license = License.new
    end

    def create
        @license.save
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :home, :login]

  def index
    @patients = Patient.all
  end

  def home
  end
  
  def new
    @patient = Patient.new
  end

  def show
    @doctors = Doctor.all
    @patient = Patient.find(params[:id])
  end

  def login
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.valid?
      @patient.save
      session[:patient_id] = @patient.id
      redirect_to patients_login_path
    else
      redirect_to new_patient_path
    end
  end

  def destroy
    @patient = Patient.where(id: params[:id]).first
    @patient.destroy
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :email, :password)
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
    def new
        @doctors = Doctor.all 
        @patients = Patient.all
        @drugs = Drug.all
        @prescription = Prescription.new
    end

    def create
        @prescription = Prescription.new(prescription_params)
        @prescription.doctor = @doctor
        @prescription.save
    end

    def show
        @prescription = Prescription.find(params[:id])
    end

    private

    def prescription_params
        params.require(:prescription).permit(:doctor_name, :patient_name, :dosage, :doctor_id, :patient_id, :drug_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
    if params[:patient]
      @patient = Patient.find_by(email: params[:email])
      if @patient && @patient.authenticate(params[:password])
        session[:patient_id] = @patient.id
        redirect_to @patient
      else
        render 'patients/login'
      end
    elsif params[:doctor]
      @doctor = Doctor.find_by(email: params[:email])
      if @doctor && @doctor.authenticate(params[:password])
        session[:doctor_id] = @doctor.id
        redirect_to @doctor
      else
        render 'doctors/login'
      end
    end
  end

  def destroy
    if session[:patient_id]
      session.delete :patient
      redirect_to patients_home_path
    elsif session[:doctor_id]
      session.delete :doctor
      redirect_to doctors_home_path
    end
  end

  def page_requires_login
  end

  def login
  end

  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/appointments/new.html.erb
<h1>Create Appointment</h1>
<%= form_for @appointment do |f| %>
    <label> Doctor name:</label><br>
    <%= f.collection_select :doctor_id, @doctors, :id, :name %><br>
    
    <label> Patient name:</label><br>
    
    <%= @patient.name %><br>
    <label> Date set:</label><br>

    <label> Time set:</label><br>
    
    <%= f.submit %>
<%end%>

app/views/doctors/home.html.erb
<h1>Welcome to Quick Prescrip for doctors</h1>

<%= button_to "Login", '/doctors/login', method: :get%>
<%= button_to "Sign Up", '/doctors/new', method: :get%>

app/views/doctors/login.html.erb
<%= render "sessions/new", user_type: "doctor" %>

app/views/doctors/new.html.erb
<h1>Sign Up</h1>
<%= form_for @doctor do |f| %>
    <label> Doctor name:</label><br>
    <%= f.text_field :name %><br>
    <label> Doctor email:</label><br>
    <%= f.text_field :email %><br>
    <label> Doctor password:</label><br>
    <%= f.password_field :password %><br>
    <label> Doctor license number:</label><br>
    <%= f.text_field :license_id %><br>
    <%= f.submit %>
<%end%>

app/views/doctors/show.html.erb
<h1> Doctor <%= @doctor.name %></h1>

<h2> Doctor appointments: </h2>
<h2> Doctor prescriptions: </h2>

<h3> Doctor patients: </h3>
<% @patients.each do |patient| %>
    <label> Patient name: </label>
    <%= patient.name %><br>
    <label> Patient email: </label>
    <%= patient.email %><br>
<% end %>

<%= button_to "Create a Prescription", '/prescriptions/new', method: :get%>
<%= button_to "Logout", '/logout', method: :post %>

app/views/patients/home.html.erb
<h1>Welcome to Quick Prescrip for patients</h1>

<%= button_to "Login", '/patients/login', method: :get%>
<%= button_to "Sign Up", '/patients/new', method: :get%>

app/views/patients/index.html.erb
<h1>All Patients</h1>

<ul>
  <% @patients.each do |patient| %>
    <li>
      <%= link_to patient.name, patient_path(patient) %>
    </li>
    <br>
  <% end %>
</ul>

app/views/patients/login.html.erb
<%= render "sessions/new", user_type: "patient" %>

app/views/patients/new.html.erb
<h1>Sign Up</h1>
<%= form_for @patient do |f| %>
    <label> Patient name:</label><br>
    <%= f.text_field :name %><br>
    <label> Patient email:</label><br>
    <%= f.text_field :email %><br>
    <label> Patient password:</label><br>
    <%= f.password_field :password %><br>
    <%= f.submit %>
<%end%>

app/views/patients/show.html.erb
<h1> Patient <%= @patient.name %></h1>

<h2> Patient appointments: </h2>
<h2> Patient prescriptions: </h2>

<h3> Patient doctors: </h3>
<% @doctors.each do |doctor| %>
    <label> Doctor name: </label>
    <%= doctor.name %><br>
    <label> Doctor email: </label>
    <%= doctor.email %><br>
<% end %>

<%= button_to "Create an Appointment", '/appointments/new', method: :get%>
<%= button_to "Logout", '/logout', method: :post %>

app/views/prescriptions/new.html.erb
<h1>Create Prescription</h1>
<%= form_for @prescription do |f| %>
    <label> Doctor name: </label><br>
    <%= @doctor.name %><br>
    <label> Patient name: </label><br>
    <%= f.collection_select :patient_id, @patients, :id, :name %><br>
    <label> Doctor signature: </label><br>
    <%= f.text_field :doctor_name %><br>
    <label> Dosage: </label><br>
    <%= f.text_field :dosage %><br>
    <label> Drug name: </label><br>
    <%= f.collection_select :drug_id, @drugs, :id, :name %><br>
    <%= f.submit %>
<%end%>

app/views/prescriptions/show.html.erb
<h1>Prescription</h1>
Drug name:
<%= @prescription.drug.name %><br>
Patient name:
<%= @prescription.patient.name %><br>
Doctor name:
<%= @prescription.doctor.name %><br>
Dosage: 
<%= @prescription.dosage %>mg<br>